# Generated by Django 3.1 on 2022-01-21 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cateogory',
            name='slug',
            field=models.SlugField(default='', max_length=100, unique=True),
        ),
    ]
